# Generated by Django 2.2.9 on 2020-07-10 09:22

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_quickbooks', '0004_auto_20200122_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('list_id', models.CharField(editable=False, max_length=127, null=True, unique=True)),
                ('edit_sequence', models.CharField(editable=False, max_length=127, null=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=41, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(null=True)),
                ('time_modified', models.DateTimeField(null=True)),
                ('company_name', models.CharField(max_length=41, null=True)),
                ('phone', models.CharField(max_length=21, null=True)),
                ('alt_phone', models.CharField(max_length=21, null=True)),
                ('fax', models.CharField(max_length=21, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.CharField(max_length=41, null=True)),
                ('alt_contact', models.CharField(max_length=41, null=True)),
                ('external_id', models.CharField(max_length=36, null=True)),
                ('external_updated_at', models.DateTimeField(null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_quickbooks.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('list_id', models.CharField(editable=False, max_length=127, null=True, unique=True)),
                ('edit_sequence', models.CharField(editable=False, max_length=127, null=True)),
                ('time_created', models.DateTimeField(null=True)),
                ('time_modified', models.DateTimeField(null=True)),
                ('txn_date', models.DateField(null=True)),
                ('is_pending', models.BooleanField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('memo', models.TextField(max_length=4095, null=True)),
                ('external_id', models.CharField(max_length=36, null=True)),
                ('external_updated_at', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='django_quickbooks.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='realm',
            name='schema_name',
        ),
        migrations.AddField(
            model_name='realm',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='ShipAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresses', jsonfield.fields.JSONField(default=dict)),
                ('city', models.CharField(max_length=31, null=True)),
                ('state', models.CharField(max_length=21, null=True)),
                ('postal_code', models.CharField(max_length=13, null=True)),
                ('country', models.CharField(max_length=31, null=True)),
                ('note', models.CharField(max_length=41, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipaddress', to='django_quickbooks.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('list_id', models.CharField(editable=False, max_length=127, null=True, unique=True)),
                ('edit_sequence', models.CharField(editable=False, max_length=127, null=True)),
                ('name', models.CharField(max_length=31)),
                ('full_name', models.CharField(max_length=159, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_id', models.CharField(editable=False, max_length=127, null=True)),
                ('account_type', models.CharField(max_length=100, null=True)),
                ('account_number', models.IntegerField(null=True)),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_accounts', to='django_quickbooks.Realm')),
            ],
        ),
        migrations.CreateModel(
            name='ItemService',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('list_id', models.CharField(editable=False, max_length=127, null=True, unique=True)),
                ('edit_sequence', models.CharField(editable=False, max_length=127, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('full_name', models.CharField(max_length=159, null=True)),
                ('parent_id', models.CharField(max_length=127, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_services', to='django_quickbooks.ServiceAccount')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_services', to='django_quickbooks.Realm')),
            ],
            options={
                'unique_together': {('name', 'realm')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField(blank=True, max_length=150, null=True)),
                ('external_id', models.CharField(max_length=36, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='django_quickbooks.Invoice')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='django_quickbooks.Realm')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_charges', to='django_quickbooks.ItemService')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='django_quickbooks.Realm'),
        ),
        migrations.AddField(
            model_name='customer',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='django_quickbooks.Realm'),
        ),
        migrations.CreateModel(
            name='BillAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresses', jsonfield.fields.JSONField(default=dict)),
                ('city', models.CharField(max_length=31, null=True)),
                ('state', models.CharField(max_length=21, null=True)),
                ('postal_code', models.CharField(max_length=13, null=True)),
                ('country', models.CharField(max_length=31, null=True)),
                ('note', models.CharField(max_length=41, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billaddress', to='django_quickbooks.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalItemService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_item_service_id', models.CharField(max_length=36)),
                ('item_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_item_service', to='django_quickbooks.ItemService')),
            ],
            options={
                'unique_together': {('item_service', 'external_item_service_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('name', 'realm')},
        ),
    ]
