# Generated by Django 2.2.9 on 2020-06-05 06:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_quickbooks', '0004_auto_20200122_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('qbd_object_id', models.CharField(editable=False, max_length=127, null=True, unique=True)),
                ('qbd_object_updated_at', models.DateTimeField(editable=False, null=True)),
                ('qbd_object_version', models.CharField(editable=False, max_length=127, null=True)),
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=41, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(null=True)),
                ('time_modified', models.DateTimeField(null=True)),
                ('edit_sequence', models.CharField(max_length=127, null=True)),
                ('company_name', models.CharField(max_length=41, null=True)),
                ('phone', models.CharField(max_length=21, null=True)),
                ('alt_phone', models.CharField(max_length=21, null=True)),
                ('fax', models.CharField(max_length=21, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.CharField(max_length=41, null=True)),
                ('alt_contact', models.CharField(max_length=41, null=True)),
                ('external_id', models.CharField(max_length=36, null=True)),
                ('external_updated_at', models.DateTimeField(null=True)),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_realm', to='django_quickbooks.Realm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('qbd_object_id', models.CharField(editable=False, max_length=127, null=True, unique=True)),
                ('qbd_object_updated_at', models.DateTimeField(editable=False, null=True)),
                ('qbd_object_version', models.CharField(editable=False, max_length=127, null=True)),
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(null=True)),
                ('time_modified', models.DateTimeField(null=True)),
                ('edit_sequence', models.CharField(max_length=127, null=True)),
                ('txn_date', models.DateField(null=True)),
                ('is_pending', models.BooleanField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('memo', models.TextField(max_length=4095, null=True)),
                ('external_id', models.CharField(max_length=36, null=True)),
                ('external_updated_at', models.DateTimeField(null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='django_quickbooks.Customer')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_realm', to='django_quickbooks.Realm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShipAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresses', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('city', models.CharField(max_length=31, null=True)),
                ('state', models.CharField(max_length=21, null=True)),
                ('postal_code', models.CharField(max_length=13, null=True)),
                ('country', models.CharField(max_length=31, null=True)),
                ('note', models.CharField(max_length=41, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipaddress', to='django_quickbooks.Invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemService',
            fields=[
                ('qbd_object_id', models.CharField(editable=False, max_length=127, null=True, unique=True)),
                ('qbd_object_updated_at', models.DateTimeField(editable=False, null=True)),
                ('qbd_object_version', models.CharField(editable=False, max_length=127, null=True)),
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemservices_realm', to='django_quickbooks.Realm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('qbd_object_id', models.CharField(editable=False, max_length=127, null=True, unique=True)),
                ('qbd_object_updated_at', models.DateTimeField(editable=False, null=True)),
                ('qbd_object_version', models.CharField(editable=False, max_length=127, null=True)),
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField(blank=True, max_length=150, null=True)),
                ('external_id', models.CharField(max_length=36, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='django_quickbooks.Invoice')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicelines_realm', to='django_quickbooks.Realm')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_charges', to='django_quickbooks.ItemService')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalItemService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_item_service_id', models.CharField(max_length=36)),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_item_service', to='django_quickbooks.ItemService')),
            ],
        ),
        migrations.CreateModel(
            name='BillAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresses', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('city', models.CharField(max_length=31, null=True)),
                ('state', models.CharField(max_length=21, null=True)),
                ('postal_code', models.CharField(max_length=13, null=True)),
                ('country', models.CharField(max_length=31, null=True)),
                ('note', models.CharField(max_length=41, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billaddress', to='django_quickbooks.Invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
