# Generated by Django 2.2.9 on 2020-06-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_quickbooks', '0005_auto_20200624_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
