# Generated by Django 2.2.9 on 2020-07-14 12:23

from django.db import migrations, models
import django_quickbooks.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_quickbooks', '0005_auto_20200710_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='is_pending',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='realm',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=django_quickbooks.models.file_path),
        ),
    ]
