# Generated by Django 2.2.9 on 2020-07-01 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_quickbooks', '0005_billaddress_customer_externalitemservice_invoice_invoiceline_itemservice_serviceaccount_shipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='django_quickbooks.Invoice'),
        ),
    ]
