# Generated by Django 2.2.9 on 2020-07-16 09:19

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('django_quickbooks', '0006_auto_20200714_1223'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='externalitemservice',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='realm',
            name='name',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
